os:
  editPreset: nvim
git:
  pagers:
    - colorArg: always
      pager: delta --light --paging=never --line-numbers
    - colorArg: always
      pager: delta --light --paging=never --line-numbers --side-by-side
    - colorArg: always
